### PR TITLE
feat: dynamic path matcher

### PR DESCRIPTION
**Pull request by boojack**
Redirect `/bytebase/star-history` to `/#bytebase/star-history`.

### CODE REVIEW

**Comment by tianzhou** [comment]
Is this just enabling a nicer URL because I thought all existing URLs use the # format?

**Comment by boojack** [comment]
> Is this just enabling a nicer URL because I thought all existing URLs use the # format?

User can go to star-history by replacing `github` with `star-history` in any GitHub repo page.

e.g. this page url is `https://github.com/bytebase/star-history/pull/152`, I can change the browser url with `https://star-history.com/bytebase/star-history/pull/152`, then it should redirect to `https://star-history.com/#bytebase/star-history`.

BTW, it's a great idea from @xiaoluoboding article.

**Review by tianzhou — APPROVED** [review]
LGTM

**Comment by tianzhou** [comment]
> > Is this just enabling a nicer URL because I thought all existing URLs use the # format?
> 
> User can go to star-history by replacing `github` with `star-history` in any GitHub repo page.
> 
> e.g. this page url is `https://github.com/bytebase/star-history/pull/152`, I can change the browser url with `https://star-history.com/bytebase/star-history/pull/152`, then it should redirect to `https://star-history.com/#bytebase/star-history`.
> 
> BTW, it's a great idea from @xiaoluoboding article.

I see, this is a wonderful idea.

**Pull request merged**
