### PR TITLE
feat: add sitemap.xml

### PR DESCRIPTION
**Pull request by boojack**
Add `sitemap.xml` generator with vite.

### CODE REVIEW

**Comment by boojack** [comment]
PTAL

**Comment by boojack** [comment]
If we published a blog by ghost, we need to rebuild project to generate the new `sitemap.xml`
And if we want the dynamic metas and sitemap.xml, I think it cannot be done in single-page application.
Is there any good solution?

**Review by xiaoluoboding — APPROVED** [review]
LGTM

**Review by tianzhou — APPROVED** [review]
LGTM

**Pull request merged**
