### PR TITLE
feat: support embed chart into other site

### PR DESCRIPTION
**Pull request by boojack**

### CODE REVIEW

**Comment by boojack** [comment]
PTAL

**Comment by tianzhou** [comment]
Let's make the dialog a bit nicer, similar to

CleanShot 2022-01-07 at 12 03 22@2x

**Comment by tianzhou** [comment]
Also it's not actually required? it's just very easy to exceed the limit?  We have 2 approaches

1. If we do require it, then we should add visual cue to indicate it's required.

2. If we don't require it, then we should warn user that in the embed case, it's likely to exceed the limit.

**Comment by tianzhou** [comment]
Also somehow, when tried myself on local machine, I am not able to load the chart, the web page says not found

**Comment by boojack** [comment]
> Also somehow, when tried myself on local machine, I am not able to load the chart, the web page says not found

It's a SPA router problem in production env, maybe we need a static file server or change the router history mode. I will figure out a good solution about it later

**Comment by boojack** [comment]
@tianzhou PTAL
1. The token is required for making sure that out chart could be present normally.
2. I find a better way with render.com to solve the router problem: https://render.com/docs/deploy-vue-js

**Review by tianzhou — APPROVED** [review]
LGTM

**Pull request merged**
