### PR TITLE
chore: “Star history” -> “Star History”

### PR DESCRIPTION
**Pull request by tianzhou**

### CODE REVIEW

**Review by Megrax — APPROVED** [review]
LGTM

**Comment by boojack** [comment]
Another that needs to be changed: https://sourcegraph.com/github.com/bytebase/star-history/-/blob/src/components/Charts/StarXYChart.vue?L64:17

**Comment by tianzhou** [comment]
> Another that needs to be changed: https://sourcegraph.com/github.com/bytebase/star-history/-/blob/src/components/Charts/StarXYChart.vue?L64:17

Done

**Comment by tianzhou** [comment]
PTAL

**Review by boojack — APPROVED** [review]
LGTM

**Review by Megrax — APPROVED** [review]
LGTM

**Pull request merged**
