### PR TITLE
Allow input multiple repos separated by comma

### PR DESCRIPTION
**Pull request by xinbenlv**
Hi Tim Qian,

This tool is awesome. I wonder if we can make it even more convenient to add multiple repo at a time, hence the PR.

I did 
```
npm run startWebsite
```
and hand tested it on my local browser. 

image

### CODE REVIEW

**Comment by timqian** [comment]
Thanks @xinbenlv, This feature should be useful, I will merge it and deploy it soon.

**Comment by luzpaz** [comment]
Please merge this feature :pray:

**Comment by tianzhou** [comment]
@xinbenlv

We made some slight changes and could you please re-sync the master and submit again?

We'd be happy to accept this. Thanks!

**Comment by boojack** [comment]
This feature has been released in https://github.com/bytebase/star-history/pull/102
Thanks for your contributing!

**Pull request closed without merging**
