### PR TITLE
Trim hashtag link

### LINKED ISSUE #158: Trim hashtag link
When the url includes a hashtag link, `star-history` says `Some unexpected error happened, try again later`.

I think the url could be trimmed by the `#` like below.

```
// Expected result
sindresorhus/p-event#install
-> Showing `sindresorhus/p-event`'s graph

// Actual result
sindresorhus/p-event#install
-> Some unexpected error happened, try again later
```

### PR DESCRIPTION
**Pull request by jopemachine**
Fixes #158.
If there's anything else I need to do, I'd appreciate letting me know :)

### CODE REVIEW

**Comment by tianzhou** [comment]
@jopemachine thanks for the contribution, please follow the cla-bot to sign first. Thanks!

**Comment by jopemachine** [comment]
> @jopemachine thanks for the contribution, please follow the cla-bot to sign first. Thanks!

I submitted the CLA form and added my nickname to [this list](https://github.com/bytebase/clabot-config/blob/main/.clabot). Is there other things I need to do?

**Review by boojack — APPROVED** [review]
LGTM! Sorry for missing this :(

**Comment by d-bytebase** [comment]
> > @jopemachine thanks for the contribution, please follow the cla-bot to sign first. Thanks!
> 
> I submitted the CLA form and added my nickname to [this list](https://github.com/bytebase/clabot-config/blob/main/.clabot). Is there other things I need to do?

Hi @jopemachine, it's a GitHub issue that it doesn't sync with latest. I'm merging the request.

**Comment by d-bytebase** [comment]
Thanks for your contribution!

**Pull request merged**
